services:
  - type: worker
    name: sete-bot
    runtime: node
    plan: free
    buildCommand: npm install && npm run deploy-commands
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: MONGODB_URI
        sync: false
